drupal_os_user: holuser
drupal_os_group: docker

# MySQL
mysql_version: 5.7
db_host: localhost
db_service: mysqld
db_port: 3306
db_name: drupal_db
db_user: drupal_user
db_user_password: 'Welcome2Drupal!'
db_root_password: 'Welcome2Drupal!'
db_user_privileges: SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,CREATE TEMPORARY TABLES,LOCK TABLES
admin_privileges:
  - '{{ db_name }}.*:ALL'
  - '*.*:SUPER,RELOAD,SHOW\ DATABASES'
#
# Drupal
#
drupal_base_path: /var/www/drupal
#drupal_trusted_host_pattern: ^mysite\.example\.com$   # regular expression
#drupal_trusted_host_pattern: ^drupal-qa\.hhs\.state\.ma\.us$
drupal_trusted_host_pattern: ^localhost$
drupal_sitename: Drupal Content Test Site
drupal_email: drupal_user@ehs.com
drupal_region: en
drupal_profile: standard
drupal_admin: admin
drupal_admin_password: Welcome2Drupal

#
# Drupal Modules
#
drupal_install_modules:
    - token
    - schema_metatag
    - ctools
    - pathauto
    - metatag

drupal_enable_modules:
    - token
    - schema_metatag
    - ctools
    - pathauto
    - metatag    
